Language: c
compiler:
    - gcc
    - clang
branches:
    only:
        - master
        - dev
before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install openssl cmake libevent-dev libjpeg-dev libgif-dev libpng-dev libwebp-dev libmagickwand-dev libmemcached-dev
script:
    - make
    - cd bin
    - ./zimg conf/zimg.lua
